spring:
  application:
    name: api-customer
  datasource:
    url: jdbc:mysql://localhost:3306/baseback
    username: root
    password: Wire2681
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka



server:
  port: 8081








