server:
  port: ${PORT:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonathanvictoricadh/dh202302-g5-config
          default-label: main
          force-pull: true
          search-paths: configData