spring:
  application:
    name: api-wallet



spring.application.name = api-wallet

spring.datasource.url=jdbc:mysql://localhost:3306/baseback
spring.datasource.username=root
spring.datasource.password=Wire2681
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port:8082

eureka.client.service-url.defaultZone= http://localhost:8761/eureka